### ISSUE TITLE
H5端，首页sh-adv模块不显示

### ISSUE THREAD

**Issue by animus198656** [ITmonkey-cn/shopro#2]

**Comment by ITmonkey-cn** [comment]
你是怎么控制广告模块的显示的~

**Comment by animus198656** [comment]
> 你是怎么控制广告模块的显示的~

直接源码运行就不显示。但是Hbuilderx内置预览和在App端可以显示

**Comment by ITmonkey-cn** [comment]
> > 你是怎么控制广告模块的显示的〜
> 
> 但是Hbuilderx内置预览和在App端可以显示

这个是后台控制的，不同端，可以展示不同的内容

**Comment by animus198656** [comment]
> > > 你是怎么控制广告模块的显示的〜
> > 
> > 
> > 但是Hbuilderx内置预览和在App端可以显示
> 
> 这个是后台控制的，不同端，可以展示不同的内容

哦，谢谢。
另一个问题，现在h5端和App端进不去了，首页提示“未找到模板”。微信小程序是正常的

**Comment by ITmonkey-cn** [comment]
> > > > 你是怎么控制广告模块的显示的〜
> > > 
> > > 
> > > 但是Hbuilderx内置预览和在App端可以显示
> > 
> > 
> > 这个是后台控制的，不同端，可以展示不同的内容
> 
> 哦，谢谢。
> 另一个问题，现在h5端和App端进不去了，首页提示“未找到模板”。微信小程是正常的
因为首页还有其他页面的模块是后台装修控制的，> > > > 你是怎么控制广告模块的显示的〜
> > > 
> > > 
> > > 但是Hbuilderx内置预览和在App端可以显示
> > 
> > 
> > 这个是后台控制的，不同端，可以展示不同的内容
> 
> 哦，谢谢。
> 另一个问题，现在h5端和App端进不去了，首页提示“未找到模板”。微信小程是正常的
因为首页还有其他页面的模块是后台装修控制的，可以分平台装修，接口也有很多区别，可能你的接口没装模板

**Comment by animus198656** [comment]
> > > > > 你是怎么控制广告模块的显示的〜
> > > > 
> > > > 
> > > > 但是Hbuilderx内置预览和在App端可以显示
> > > 
> > > 
> > > 这个是后台控制的，不同端，可以展示不同的内容
> > 
> > 
> > 哦，谢谢。
> > 另一个问题，现在h5端和App端进不去了，首页提示“未找到模板”。微信小程是正常的
> > 因为首页还有其他页面的模块是后台装修控制的，> > > > 你是怎么控制广告模块的显示的〜
> > > > 但是Hbuilderx内置预览和在App端可以显示
> > > 
> > > 
> > > 这个是后台控制的，不同端，可以展示不同的内容
> > 
> > 
> > 哦，谢谢。
> > 另一个问题，现在h5端和App端进不去了，首页提示“未找到模板”。微信小程是正常的
> > 因为首页还有其他页面的模块是后台装修控制的，可以分平台装修，接口也有很多区别，可能你的接口没装模板

我没有用自己的接口，是用的你们的接口。你们官网不是有个项目演示用的h5二维码吗，你用手机浏览器扫下就能看到问题了

**Comment by ITmonkey-cn** [comment]
可以了，多谢反馈，后台没有配置
